django_sqlalchemy/dlt/downloader/urls.py
from django.conf.urls.defaults import *
from django.views.generic.create_update import create_object

from dlt.downloader import views, views_sa, models

extra_data = {
      'model': models.DownloadItem,
      'template_name': 'create_item.html',
      'post_save_redirect': '..',
              }

urlpatterns = patterns('',
    # Example:
    (r'^$', views.list_items),
    (r'^alchemy/$', views_sa.list_items),
    (r'^create/$', views.create_item, extra_data)
)

django_sqlalchemy/dlt/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    # Example:
    (r'^dlt/', include('dlt.downloader.urls')),

    # Uncomment this for admin:
     (r'^admin/', include('django.contrib.admin.urls')),
     
)

django_sqlalchemy/dlt/downloader/models.py
from django.db import models
import datetime

class DownloadItem(models.Model):
    
    class Admin:
        pass

    class Meta:
        get_latest_by = 'added_at'
    
    url = models.CharField(maxlength=255, null=False)
    added_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(null=True, blank=True)
    finished_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.url
    
    def is_started(self):
        return self.started_at is not None and datetime.datetime.now() > self.started_at
    
    def is_finished(self):
        return self.finished_at is not None and datetime.datetime.now() > self.finished_at
    

django_sqlalchemy/dlt/downloader/views.py
# Create your views here.

from django.shortcuts import render_to_response
from django.views.generic.create_update import create_object
from dlt.downloader import models

def list_items(request):
    items = models.DownloadItem.objects.all()
    context = {'items': items}
    return render_to_response('list_items.html', context)

def create_item(*args, **kwargs):
    return create_object(*args, **kwargs)

django_sqlalchemy/dlt/templates/base.html
<html>
<head>
<title>Django Live Tutorial</title>
{{ meta }}
</head>
<body>
{% block content %}
	Этот текст видно только в базовом шаблоне.
{% endblock %}
</body>
</html>

django_sqlalchemy/dlt/templates/create_item.html
{% extends "base.html" %}

{% block content %}

{% if form.has_errors %}
Ошибка!
{% endif %}

<form action='.' method='post'>

	<label for="id_url">Адрес</label>
	{{ form.url }}
	{% if form.url.errors %}*** {{ form.url.errors|join:", " }} {% endif %}
	

	<input type="submit" value="Создать" />

</form>

{% endblock %}

django_sqlalchemy/dlt/templates/list_items.html
{% extends "base.html" %}

{% block content %}
<small>
{% if is_sqlalchemy %}
    <a href="{% url downloader.views.list_items %}">Использовать Django ORM</a> 
{% else %}
    <a href="{% url downloader.views_sa.list_items %}">Использовать SQLAlchemy ORM</a> 
{% endif %}
</small>

{% regroup items by is_finished as grouped %}
{% for group in grouped %}

<h1>{{ group.grouper|yesno:"Завершены,В очереди" }}</h1>
<ul>
{% for item in group.list %}
<li>
<a href="{{ item.url }}">{{ item }}</a> --

{% if item.is_finished %}
	завершен {{ item.finished_at }}
{% else %}
	{% if item.is_started %}
		начат {{ item.started_at }}
	{% else %}
		добавлен {{ item.added_at }}
	{% endif %}
{% endif %}

</li>
{% endfor %}
</ul>
{% endfor %}

<a href="{% url downloader.views.create_item %}">Добавить</a>

{% endblock %}